matrix:
  include:
    # Concurrent osx jobs is limited to 2 while up to 5 jobs may run
    # simultaneously. With the osx jobs on top, the osx jobs will be
    # queued first, not last.
    - os: osx
      osx_image: xcode9.4
      language: c++
      compiler: clang
      addons:
        homebrew:
          packages:
            - graphviz
          update: true
      env:
        - NORMALIZ_VERSION=3.5.4
        - PYTHON_INSTALL='sudo -H pip install'
      before_install:
        - brew link --overwrite python

    - os: osx
      osx_image: xcode9.4
      language: c++
      compiler: clang
      addons:
        homebrew:
          packages:
            - graphviz
          update: true
      env:
        - NORMALIZ_VERSION=3.6.0
        - PYTHON_INSTALL='sudo -H pip install'
      before_install:
        - brew link --overwrite python

    - os: osx
      osx_image: xcode10
      language: c++
      compiler: clang
      addons:
        homebrew:
          packages:
            - graphviz
          update: true
      env:
        - NORMALIZ_VERSION=3.6.0
        - PYTHON_INSTALL='sudo -H pip install'
      before_install:
        - brew link --overwrite python

    - os: osx
      osx_image: xcode10.1
      language: c++
      compiler: clang
      addons:
        homebrew:
          packages:
            - graphviz
          update: true
      env:
        - NORMALIZ_VERSION=3.6.0
        - PYTHON_INSTALL='sudo -H pip install'
      before_install:
        - brew link --overwrite python

    - os: osx
      osx_image: xcode10.2
      language: c++
      compiler: clang
      addons:
        homebrew:
          packages:
            - graphviz
          update: true
      env:
        - NORMALIZ_VERSION=3.6.2
        - PYTHON_INSTALL='sudo -H pip install'
      before_install:
        - brew link --overwrite python

    - os: osx
      osx_image: xcode10.3
      language: c++
      compiler: clang
      addons:
        homebrew:
          packages:
            - graphviz
          update: true
      env:
        - NORMALIZ_VERSION=3.4.0
        - PYTHON_INSTALL='sudo -H pip install'
      before_install:
        - brew link --overwrite python

    - os: osx
      osx_image: xcode10.3
      language: c++
      compiler: clang
      addons:
        homebrew:
          packages:
            - graphviz
          update: true
      env:
        - NORMALIZ_VERSION=3.5.4
        - PYTHON_INSTALL='sudo -H pip install'
      before_install:
        - brew link --overwrite python

    - os: osx
      osx_image: xcode10.3
      language: c++
      compiler: clang
      addons:
        homebrew:
          packages:
            - graphviz
          update: true
      env:
        - NORMALIZ_VERSION=3.7.3
        - PYTHON_INSTALL='sudo -H pip install'
      before_install:
        - brew link --overwrite python


    - os: osx
      osx_image: xcode11
      language: c++
      compiler: clang
      addons:
        homebrew:
          packages:
            - graphviz
          update: true
      env:
        - NORMALIZ_VERSION=3.7.3
        - PYTHON_INSTALL='sudo -H pip install'
      before_install:
        # install numpy using pip rather than homebrew
        - brew uninstall numpy --ignore-dependencies
        - brew link --overwrite python

    - os: osx
      osx_image: xcode11
      language: c++
      compiler: clang
      addons:
        homebrew:
          packages:
            - graphviz
          update: true
      env:
        - NORMALIZ_VERSION=3.7.4
        - PYTHON_INSTALL='sudo -H pip install'
      before_install:
        - brew uninstall numpy --ignore-dependencies
        - brew link --overwrite python

    - os: osx
      osx_image: xcode11.1
      language: c++
      compiler: clang
      addons:
        homebrew:
          packages:
            - graphviz
          update: true
      env:
        - NORMALIZ_VERSION=3.8.1
        - PYTHON_INSTALL='sudo -H pip install'
      before_install:
        - brew uninstall numpy --ignore-dependencies
        - brew link --overwrite python

    - os: osx
      osx_image: xcode11.2
      language: c++
      compiler: clang
      addons:
        homebrew:
          packages:
            - graphviz
          update: true
      env:
        - NORMALIZ_VERSION=3.8.1
        - PYTHON_INSTALL='sudo -H pip install'
      before_install:
        - brew uninstall numpy --ignore-dependencies
        - brew link --overwrite python

    - os: osx
      osx_image: xcode11.3
      language: c++
      compiler: clang
      addons:
        homebrew:
          packages:
            - graphviz
          update: true
      env:
        - NORMALIZ_VERSION=3.8.2
        - PYTHON_INSTALL='sudo -H pip install'
      before_install:
        - brew uninstall numpy --ignore-dependencies
        - brew link --overwrite python

    - os: osx
      osx_image: xcode11.4
      language: c++
      compiler: clang
      addons:
        homebrew:
          packages:
            - graphviz
          update: true
      env:
        - NORMALIZ_VERSION=3.8.5
        - PYTHON_INSTALL='sudo -H pip install'
      before_install:
        - brew uninstall numpy --ignore-dependencies
        - brew link --overwrite python

    - os: osx
      osx_image: xcode11.5
      language: c++
      compiler: clang
      addons:
        homebrew:
          packages:
            - graphviz
          update: true
      env:
        - NORMALIZ_VERSION=3.8.5
        - PYTHON_INSTALL='sudo -H pip install'
      before_install:
        - brew uninstall numpy --ignore-dependencies
        - brew link --overwrite python

    - os: osx
      osx_image: xcode11.6
      language: c++
      compiler: clang
      addons:
        homebrew:
          packages:
            - graphviz
          update: true
      env:
        - NORMALIZ_VERSION=3.8.5
        - PYTHON_INSTALL='sudo -H pip install'
      before_install:
        - brew uninstall numpy --ignore-dependencies
        - brew link --overwrite python

    - os: osx
      osx_image: xcode12
      language: c++
      compiler: clang
      addons:
        homebrew:
          packages:
            - graphviz
          update: true
      env:
        - NORMALIZ_VERSION=3.8.5
        - PYTHON_INSTALL='sudo -H pip install'
      before_install:
        - brew uninstall numpy --ignore-dependencies
        - brew link --overwrite python

    - os: osx
      osx_image: xcode12u
      language: c++
      compiler: clang
      addons:
        homebrew:
          packages:
            - graphviz
          update: true
      env:
        - NORMALIZ_VERSION=3.8.7
        - NORMALIZ_ZIP_BASE=normaliz-${NORMALIZ_VERSION}-
        - PYTHON_INSTALL='sudo -H pip install'
      before_install:
        - brew uninstall numpy --ignore-dependencies
        - brew link --overwrite python

    - os: osx
      osx_image: xcode12u
      language: c++
      compiler: clang
      addons:
        homebrew:
          packages:
            - graphviz
            - pyenv
          update: true
      env:
        - NORMALIZ_VERSION=3.8.7
        - NORMALIZ_ZIP_BASE=normaliz-${NORMALIZ_VERSION}-
        - PYTHON_INSTALL='sudo -H pip install'
      before_install:
        - brew uninstall numpy --ignore-dependencies
        - pyenv install 3.8.5
        - pyenv global 3.8.5
        - pyenv version
        - if command -v pyenv 1>/dev/null 2>&1; then eval "$(pyenv init -)"; fi

    - os: osx
      osx_image: xcode12.2
      language: c++
      compiler: clang
      addons:
        homebrew:
          packages:
            - graphviz
          update: true
      env:
        - NORMALIZ_VERSION=3.8.7
        - NORMALIZ_ZIP_BASE=normaliz-${NORMALIZ_VERSION}-
        - PYTHON_INSTALL='sudo -H pip install'
      before_install:
        - brew uninstall numpy --ignore-dependencies
        - brew link --overwrite python

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - texlive-full
            - graphviz
      env:
        - MATRIX_EVAL="export CC=gcc-6 && export CXX=g++-6"
        - NORMALIZ_VERSION=3.3.0
      before_install:
        - eval ${MATRIX_EVAL}
      python: 2.7
      language: python

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - texlive-full
            - graphviz
      env:
        - MATRIX_EVAL="export CC=gcc-7 && export CXX=g++-7"
        - NORMALIZ_VERSION=3.4.0
      before_install:
        - eval ${MATRIX_EVAL}
      python: 2.7
      language: python

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - texlive-full
            - graphviz
      env:
        - MATRIX_EVAL="export CC=gcc-7 && export CXX=g++-7"
        - NORMALIZ_VERSION=3.7.4
      before_install:
        - eval ${MATRIX_EVAL}
      python: 2.7
      language: python

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - texlive-full
            - graphviz
      env:
        - MATRIX_EVAL="export CC=gcc-8 && export CXX=g++-8"
        - NORMALIZ_VERSION=3.5.4
      before_install:
        - eval ${MATRIX_EVAL}
      python: 2.7
      language: python

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - texlive-full
            - graphviz
      env:
        - MATRIX_EVAL="export CC=gcc-6 && export CXX=g++-6"
        - NORMALIZ_VERSION=3.4.0
      before_install:
        - eval ${MATRIX_EVAL}
      python: 3.5
      language: python

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - texlive-full
            - graphviz
      env:
        - MATRIX_EVAL="export CC=gcc-7 && export CXX=g++-7"
        - NORMALIZ_VERSION=3.3.0
      before_install:
        - eval ${MATRIX_EVAL}
      python: 3.5
      language: python

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - texlive-full
            - graphviz
      env:
        - MATRIX_EVAL="export CC=gcc-8 && export CXX=g++-8"
        - NORMALIZ_VERSION=3.5.4
      before_install:
        - eval ${MATRIX_EVAL}
      python: 3.5
      language: python

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - texlive-full
            - graphviz
      env:
        - MATRIX_EVAL="export CC=gcc-6 && export CXX=g++-6"
        - NORMALIZ_VERSION=3.3.0
      python: 3.6
      before_install:
        - eval ${MATRIX_EVAL}
      language: python

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - texlive-full
            - graphviz
      env:
        - MATRIX_EVAL="export CC=gcc-8 && export CXX=g++-8"
        - NORMALIZ_VERSION=3.6.2
      before_install:
        - eval ${MATRIX_EVAL}
      python: 3.5
      language: python

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - texlive-full
            - graphviz
      env:
        - MATRIX_EVAL="export CC=gcc-6 && export CXX=g++-6"
        - NORMALIZ_VERSION=3.3.0
      python: 3.6
      before_install:
        - eval ${MATRIX_EVAL}
      language: python

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - texlive-full
            - graphviz
      env:
        - MATRIX_EVAL="export CC=gcc-8 && export CXX=g++-8"
        - NORMALIZ_VERSION=3.4.0
      python: 3.6
      before_install:
        - eval ${MATRIX_EVAL}
      language: python

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - texlive-full
            - graphviz
      env:
        - MATRIX_EVAL="export CC=gcc-8 && export CXX=g++-8"
        - NORMALIZ_VERSION=3.8.1
      python: 3.6
      before_install:
        - eval ${MATRIX_EVAL}
      language: python

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - texlive-full
            - graphviz
      env:
        - MATRIX_EVAL="export CC=gcc-7 && export CXX=g++-7"
        - NORMALIZ_VERSION=3.6.0
      python: 3.6
      before_install:
        - eval ${MATRIX_EVAL}
      language: python

    - os: linux
      dist: xenial # required for Python >= 3.7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
            - texlive-full
            - graphviz
      env:
        - MATRIX_EVAL="export CC=gcc-9 && export CXX=g++-9"
        - NORMALIZ_VERSION=3.7.3
      python: 3.7
      before_install:
        - eval ${MATRIX_EVAL}
      language: python

    - os: linux
      dist: xenial # required for Python >= 3.7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
            - texlive-full
            - graphviz
      env:
        - MATRIX_EVAL="export CC=gcc-9 && export CXX=g++-9"
        - NORMALIZ_VERSION=3.7.4
      python: 3.7
      before_install:
        - eval ${MATRIX_EVAL}
      language: python

    - os: linux
      dist: xenial # required for Python >= 3.7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
            - texlive-full
            - graphviz
      env:
        - MATRIX_EVAL="export CC=gcc-9 && export CXX=g++-9"
        - NORMALIZ_VERSION=3.8.2
      python: 3.8
      before_install:
        - eval ${MATRIX_EVAL}
      language: python

    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-10
            - texlive-full
            - graphviz
      env:
        - MATRIX_EVAL="export CC=gcc-10 && export CXX=g++-10"
        - NORMALIZ_VERSION=3.8.5
      python: 3.8
      before_install:
        - eval ${MATRIX_EVAL}
      language: python

install:
  - export PROCESSES=4
  - export NOSETESTS_TIMEOUT=600
  - export PATH=${TRAVIS_BUILD_DIR}/dist_install/bin:$PATH
  - export SECDEC_CONTRIB=${TRAVIS_BUILD_DIR}/dist_install/
  - export PYTHONPATH=${TRAVIS_BUILD_DIR}/dist_install/pySecDec_install:$PYTHONPATH
  - export PYTHON_MAJOR_VERSION=`python -c 'from sys import version_info; print(version_info.major)'`
  - if [ "x${PYTHON_INSTALL}" == "x" ]; then export PYTHON_INSTALL='pip install'; fi
  - echo running on $TRAVIS_OS_NAME
  - echo using CXX=$CXX
  - python --version
  - $PYTHON_INSTALL --upgrade pip setuptools wheel
  - $PYTHON_INSTALL nose
  # python2 support is dropped in sphinx-2
  - if [ "$PYTHON_MAJOR_VERSION" == "2" ]; then $PYTHON_INSTALL 'numpy<1.17' 'sphinx<2' 'sympy'; else $PYTHON_INSTALL -r requirements.txt --only-binary=numpy; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then make thin-dist; else make dist; fi
  - mv pySecDec-*/ dist_install
  - cd dist_install
  - make -j${PROCESSES}
  - mv pySecDec-*/ pySecDec_install/
  - if [ "x$NORMALIZ_ZIP_BASE" == "x" ]; then NORMALIZ_ZIP_BASE=normaliz-${NORMALIZ_VERSION}; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then curl -L https://github.com/Normaliz/Normaliz/releases/download/v${NORMALIZ_VERSION}/${NORMALIZ_ZIP_BASE}MacOs.zip -o normaliz.zip; else curl -L https://github.com/Normaliz/Normaliz/releases/download/v${NORMALIZ_VERSION}/${NORMALIZ_ZIP_BASE}Linux64.zip -o normaliz.zip; fi
  - unzip normaliz.zip
  - mv normaliz-${NORMALIZ_VERSION}/* bin/
  - cd ..

script:
  - nosetests --processes=${PROCESSES} --process-timeout=${NOSETESTS_TIMEOUT}
  - make util-check -j${PROCESSES}
  - make doctest -j${PROCESSES}
  - make -C high_level_tests runselected -j${PROCESSES} && make -C high_level_tests summarize-selected
