name: Full Check
on:
  workflow_dispatch:
jobs:
  check:
    name: Make Check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.6, 3.8]
        os: [ubuntu-latest]
    steps:
    - name: Install dependencies
      run: |
        if ! dpkg -s graphviz normaliz nauty libgsl-dev; then
          sudo apt-get install graphviz normaliz nauty libgsl-dev
        fi
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/checkout@v2
    - name: Install Python dependencies
      run: |
        make dependencies
    - name: Build
      run: |
        make build
    - name: Nose Check
      run: |
        python3 -m nose --processes=2 --process-timeout=600 pySecDec
    - name: Build HTML documentation
      run: |
        make doc-html
    - name: Doc Test
      run: |
        export PYTHONPATH=$PWD
        make doctest
    - name: Util Check
      run: |
        export PYTHONPATH=$PWD
        make util-check -j2
    - name: High-level Tests
      run: |
        export PYTHONPATH=$PWD
        make -C high_level_tests runtests -j2
    - name: High-level Test Summary
      run: |
        export PYTHONPATH=$PWD
        make -C high_level_tests summarize
