name: Full Check
on:
  workflow_dispatch:
jobs:
  check:
    name: Make Check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.6, 3.8]
        os: [ubuntu-latest]
    steps:
    - name: Install dependencies
      run: |
        if ! dpkg -s graphviz normaliz nauty libgsl-dev; then
          sudo apt-get install graphviz normaliz nauty libgsl-dev
        fi
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        make dependencies
    - name: Install pySecDec
      run: |
        python -m pip install .
    - uses: actions/checkout@v2
    - name: Check
      run: |
        make check
    - name: Make distribution files
      run: |
        make dist
    - name: Build HTML documentation
      run: |
        make doc-html
    - name: High-level Tests
      run: |
        make -C high_level_tests runtests -j2
    - name: High-level Test Summary
      run: |
        make -C high_level_tests summarize
